[toolchain]
channel = "nightly"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "rust-analyzer"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown"
]
profile = "default" 