# Window Configuration
[window]
width = 1920
height = 1080
fullscreen = false
vsync = true

# Graphics Configuration
[graphics]
shadow_quality = "High"
texture_quality = "High"
view_distance = 1000.0
particle_quality = "High"

# Physics Configuration
[physics]
physics_fps = 60
substeps = 2
gravity = -9.81

# Audio Configuration
[audio]
master_volume = 1.0
music_volume = 0.8
sfx_volume = 1.0 